=begin
#VisWiz.io API Documentation

#This SDK allows you to query and create new projects, builds or images within the VisWiz service. 

OpenAPI spec version: 1.1.0
Contact: support@viswiz.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ViswizSdk::AccountApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AccountApi' do
  before do
    # run before each test
    @instance = ViswizSdk::AccountApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountApi' do
    it 'should create an instance of AccountApi' do
      expect(@instance).to be_instance_of(ViswizSdk::AccountApi)
    end
  end

  # unit tests for create_webhook
  # Create a new webhook
  # When a build comparison is finished a POST HTTP request will be triggered towards all webhooks configured for the account.  The following query parameters are sent with each request:  - &#x60;branch&#x60; - &#x60;buildID&#x60; - &#x60;comparisonBranch&#x60; - &#x60;comparisonBuildID&#x60; - &#x60;diffImagesCount&#x60; - &#x60;diffPercentage&#x60; - &#x60;imagesCount&#x60; - &#x60;projectID&#x60; 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [WebHook]
  describe 'create_webhook test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_account
  # Get account info
  # Get the current account information 
  # @param [Hash] opts the optional parameters
  # @return [Account]
  describe 'get_account test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_webhooks
  # Get all webhooks
  # Get the list of webhooks configured for the account. 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2001]
  describe 'get_webhooks test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
