=begin
#VisWiz.io API Documentation

#This SDK allows you to query and create new projects, builds or images within the VisWiz service. 

OpenAPI spec version: 1.1.0
Contact: support@viswiz.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ViswizSdk::ImagesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ImagesApi' do
  before do
    # run before each test
    @instance = ViswizSdk::ImagesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ImagesApi' do
    it 'should create an instance of ImagesApi' do
      expect(@instance).to be_instance_of(ViswizSdk::ImagesApi)
    end
  end

  # unit tests for create_image
  # Create an image
  # Upload a new image for a build. This endpoint accepts only one PNG image per request.  This request requires a &#x60;Content-Type: multipart/form-data&#x60; HTTP header. 
  # @param build_id The requested build ID
  # @param name The name of the image
  # @param image The contents of the image
  # @param [Hash] opts the optional parameters
  # @return [Image]
  describe 'create_image test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_images
  # Get images for a build
  # Get a list of all images for a build. 
  # @param build_id The requested build ID
  # @param [Hash] opts the optional parameters
  # @return [Images]
  describe 'get_images test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
