=begin
#VisWiz.io API Documentation

#This SDK allows you to query and create new projects, builds or images within the VisWiz service. 

OpenAPI spec version: 1.1.0
Contact: support@viswiz.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ViswizSdk::PlansApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PlansApi' do
  before do
    # run before each test
    @instance = ViswizSdk::PlansApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PlansApi' do
    it 'should create an instance of PlansApi' do
      expect(@instance).to be_instance_of(ViswizSdk::PlansApi)
    end
  end

  # unit tests for cancel_plan
  # Cancel the active plan
  # Cancels the active subscription plan for the account. 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'cancel_plan test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_plans
  # Get all plans
  # Get a list of all the subscription plans available. 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse200]
  describe 'get_plans test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
