=begin
#VisWiz.io API Documentation

#This SDK allows you to query and create new projects, builds or images within the VisWiz service. 

OpenAPI spec version: 1.1.0
Contact: support@viswiz.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ViswizSdk::ProjectsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProjectsApi' do
  before do
    # run before each test
    @instance = ViswizSdk::ProjectsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProjectsApi' do
    it 'should create an instance of ProjectsApi' do
      expect(@instance).to be_instance_of(ViswizSdk::ProjectsApi)
    end
  end

  # unit tests for create_project
  # Create a project
  # Create a new project for the account. 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [Project]
  describe 'create_project test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_project_notifications
  # Get notifications settings
  # Get the notifications settings for a project. 
  # @param project_id The requested project ID
  # @param [Hash] opts the optional parameters
  # @return [Notifications]
  describe 'get_project_notifications test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_projects
  # Get all projects
  # Get a list of all the projects for the account. 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2002]
  describe 'get_projects test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_project_notifications
  # Update notifications settings
  # Update the notifications settings for a project. All fields are optional. 
  # @param project_id The requested project ID
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [Notifications]
  describe 'update_project_notifications test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
