=begin
#VisWiz.io API Documentation

#This SDK allows you to query and create new projects, builds or images within the VisWiz service. 

OpenAPI spec version: 1.1.0
Contact: support@viswiz.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

# Common files
require 'viswiz_sdk/api_client'
require 'viswiz_sdk/api_error'
require 'viswiz_sdk/version'
require 'viswiz_sdk/configuration'

# Models
require 'viswiz_sdk/models/account'
require 'viswiz_sdk/models/account_api_keys'
require 'viswiz_sdk/models/account_plan'
require 'viswiz_sdk/models/body'
require 'viswiz_sdk/models/body_1'
require 'viswiz_sdk/models/body_2'
require 'viswiz_sdk/models/build'
require 'viswiz_sdk/models/build_results'
require 'viswiz_sdk/models/build_results_images'
require 'viswiz_sdk/models/builds'
require 'viswiz_sdk/models/diff_image'
require 'viswiz_sdk/models/image'
require 'viswiz_sdk/models/images'
require 'viswiz_sdk/models/inline_response_200'
require 'viswiz_sdk/models/inline_response_200_1'
require 'viswiz_sdk/models/inline_response_200_2'
require 'viswiz_sdk/models/notifications'
require 'viswiz_sdk/models/plan'
require 'viswiz_sdk/models/plan_price'
require 'viswiz_sdk/models/project'
require 'viswiz_sdk/models/web_hook'

# APIs
require 'viswiz_sdk/api/account_api'
require 'viswiz_sdk/api/builds_api'
require 'viswiz_sdk/api/images_api'
require 'viswiz_sdk/api/plans_api'
require 'viswiz_sdk/api/projects_api'

module ViswizSdk
  class << self
    # Customize default settings for the SDK using block.
    #   ViswizSdk.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
